name: CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make Gradle script executable
        run: chmod +x ./gradlew
      - name: Compilar proyecto
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: danielsabana/example
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.USUARIO_DOCKER }}
          password: ${{ secrets.DOCKER_CLAVE }}